# Generated by Django 6.0.7 on 2026-07-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('item_name', models.CharField(max_length=150)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('min_threshold', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='pcs', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['item_name'],
                'indexes': [models.Index(fields=['sku'], name='inventory_i_sku_e27286_idx')],
            },
        ),
    ]
