# Generated by Django 6.0.7 on 2026-07-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='dispatched_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='open_purchase_orders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]