# Generated by Django 5.2.15 on 2026-07-27 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='volunteer',
            new_name='volunteers__volunte_b51d6f_idx',
            old_name='volunteers__volunte_5b6b6a_idx',
        ),
        migrations.RenameIndex(
            model_name='volunteer',
            new_name='volunteers__status_6d3213_idx',
            old_name='volunteers__status_7c2f11_idx',
        ),
        migrations.RenameIndex(
            model_name='volunteer',
            new_name='volunteers__is_volu_64011e_idx',
            old_name='volunteers__is_volu_3d9a02_idx',
        ),
    ]
