# Generated by Django 5.2.15 on 2026-07-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_volunteer_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('volunteer_approval_required', 'Volunteer Approval Required'), ('new_volunteer_application', 'New Volunteer Application'), ('status_update', 'Status Update'), ('announcement_urgent', 'Urgent Announcement'), ('announcement_important', 'Important Announcement')], max_length=40),
        ),
    ]
