# Generated by Django 5.2.15 on 2026-07-31 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        ('volunteers', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='incidents.incidentreport'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('volunteer_approval_required', 'Volunteer Approval Required'), ('new_volunteer_application', 'New Volunteer Application'), ('status_update', 'Status Update'), ('announcement_urgent', 'Urgent Announcement'), ('announcement_important', 'Important Announcement'), ('incident_reported', 'New Incident Reported'), ('incident_response', 'Incident Response')], max_length=40),
        ),
    ]
