# Generated by Django 5.2.15 on 2026-07-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0006_duty_and_duty_notifications'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='duty',
            new_name='volunteers__duty_co_3b9fc1_idx',
            old_name='volunteers_duty_co_idx',
        ),
        migrations.RenameIndex(
            model_name='duty',
            new_name='volunteers__status_e11ef6_idx',
            old_name='volunteers_duty_status_idx',
        ),
        migrations.RenameIndex(
            model_name='duty',
            new_name='volunteers__volunte_008d29_idx',
            old_name='volunteers_duty_vol_date_idx',
        ),
    ]
