# Generated by Django 5.2.15 on 2026-07-31 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0007_rename_volunteers_duty_co_idx_volunteers__duty_co_3b9fc1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='pre_swap_status',
            field=models.CharField(blank=True, choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('help_requested', 'Help Requested'), ('swap_requested', 'Swap Requested')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='duty',
            name='swap_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duty',
            name='swap_requested_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requests_incoming', to='volunteers.volunteer'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('help_requested', 'Help Requested'), ('swap_requested', 'Swap Requested')], default='assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('volunteer_approval_required', 'Volunteer Approval Required'), ('new_volunteer_application', 'New Volunteer Application'), ('status_update', 'Status Update'), ('announcement_urgent', 'Urgent Announcement'), ('announcement_important', 'Important Announcement'), ('incident_reported', 'New Incident Reported'), ('incident_response', 'Incident Response'), ('duty_assigned', 'Duty Assigned'), ('duty_completed', 'Duty Completed'), ('duty_help_requested', 'Duty Help/Swap Requested'), ('duty_status_update', 'Duty Status Update'), ('duty_swap_response', 'Duty Swap Response')], max_length=40),
        ),
    ]
