# Generated by Django 5.2.15 on 2026-08-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0008_duty_pre_swap_status_duty_swap_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duty',
            name='pre_swap_status',
            field=models.CharField(blank=True, choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('help_requested', 'Help Requested'), ('swap_requested', 'Swap Requested')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='duty',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('help_requested', 'Help Requested'), ('swap_requested', 'Swap Requested')], default='assigned', max_length=20),
        ),
    ]
