# Generated by Django 5.2.15 on 2026-08-01 13:07

import django.db.models.deletion
import volunteers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0009_duty_accepted_at_alter_duty_pre_swap_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(default=volunteers.models.generate_meal_session_code, max_length=20, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('qr_secret', models.CharField(default=volunteers.models.generate_qr_secret, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_sessions_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_code', models.CharField(default=volunteers.models.generate_checkin_code, max_length=20, unique=True)),
                ('assigned_role', models.CharField(blank=True, max_length=100)),
                ('shift_timing', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('checked_in', 'Checked In'), ('checked_out', 'Checked Out')], default='checked_in', max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('scan_count', models.PositiveIntegerField(default=1)),
                ('device_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_checkins', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='volunteers.mealsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='mealsession',
            index=models.Index(fields=['is_active', 'start_time', 'end_time'], name='volunteers__is_acti_0c0a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='mealcheckin',
            index=models.Index(fields=['session', 'volunteer'], name='volunteers__session_78fb3e_idx'),
        ),
        migrations.AddIndex(
            model_name='mealcheckin',
            index=models.Index(fields=['session', 'status'], name='volunteers__session_34eb50_idx'),
        ),
        migrations.AddConstraint(
            model_name='mealcheckin',
            constraint=models.UniqueConstraint(fields=('session', 'volunteer'), name='one_checkin_per_volunteer_per_session'),
        ),
    ]
