# Generated by Django 5.2.15 on 2026-08-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0010_mealsession_mealcheckin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcheckin',
            name='qr_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
