# Generated by Django 5.2.15 on 2026-08-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0011_mealcheckin_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealcheckin',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('volunteer_approval_required', 'Volunteer Approval Required'), ('new_volunteer_application', 'New Volunteer Application'), ('status_update', 'Status Update'), ('announcement_urgent', 'Urgent Announcement'), ('announcement_important', 'Important Announcement'), ('incident_reported', 'New Incident Reported'), ('incident_response', 'Incident Response'), ('duty_assigned', 'Duty Assigned'), ('duty_completed', 'Duty Completed'), ('duty_help_requested', 'Duty Help/Swap Requested'), ('duty_status_update', 'Duty Status Update'), ('duty_swap_response', 'Duty Swap Response'), ('meal_session_open', 'Meal Session Open')], max_length=40),
        ),
    ]
