# Generated by Django 5.2.15 on 2026-08-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0012_remove_mealcheckin_qr_code_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealsession',
            name='meal_name',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks')], default='lunch', max_length=20),
        ),
    ]
