# Generated by Django 5.2.15 on 2026-08-03 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
        ('volunteers', '0013_mealsession_meal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_sos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sos.sosalert'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('volunteer_approval_required', 'Volunteer Approval Required'), ('new_volunteer_application', 'New Volunteer Application'), ('status_update', 'Status Update'), ('announcement_urgent', 'Urgent Announcement'), ('announcement_important', 'Important Announcement'), ('incident_reported', 'New Incident Reported'), ('incident_response', 'Incident Response'), ('duty_assigned', 'Duty Assigned'), ('sos_alert', 'Emergency SOS'), ('sos_response', 'SOS Response'), ('duty_completed', 'Duty Completed'), ('duty_help_requested', 'Duty Help/Swap Requested'), ('duty_status_update', 'Duty Status Update'), ('duty_swap_response', 'Duty Swap Response'), ('meal_session_open', 'Meal Session Open')], max_length=40),
        ),
    ]
