# Generated by Django 6.0.7 on 2026-07-25 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devotees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('slots_per_day', models.PositiveIntegerField(default=1)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('priest', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='bookings_se_categor_59c4c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField()),
                ('slot', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('channel', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('counter', 'Counter'), ('whatsapp', 'WhatsApp')], default='web', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('devotee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='devotees.devotee')),
                ('seva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.seva')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking_code'], name='bookings_bo_booking_51e913_idx'), models.Index(fields=['date'], name='bookings_bo_date_e2d163_idx'), models.Index(fields=['status'], name='bookings_bo_status_233e96_idx')],
            },
        ),
    ]
