# Generated by Django 5.2.15 on 2026-08-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_seva_is_popular'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='seva',
            new_name='bookings_se_is_popu_96c24e_idx',
            old_name='bookings_se_is_popu_idx',
        ),
    ]
