# Generated by Django 5.2.15 on 2026-08-07 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_rename_bookings_se_is_popu_idx_bookings_se_is_popu_96c24e_idx'),
        ('devotees', '0004_devotee_guest_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='encrypted_qr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='qr_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='qr_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='used_by_volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seva_bookings_scanned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MealBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('meal_name', models.CharField(max_length=150)),
                ('meal_date', models.DateField()),
                ('meal_time', models.CharField(max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encrypted_qr', models.TextField(blank=True, default='')),
                ('qr_generated_at', models.DateTimeField(blank=True, null=True)),
                ('qr_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('devotee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_bookings', to='devotees.devotee')),
                ('used_by_volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_bookings_scanned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking_code'], name='bookings_me_booking_b2a39f_idx'), models.Index(fields=['meal_date'], name='bookings_me_meal_da_f068f4_idx'), models.Index(fields=['status'], name='bookings_me_status_714c7e_idx')],
            },
        ),
    ]
