# Generated by Django 5.2.15 on 2026-08-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_encrypted_qr_booking_is_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seva',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seva',
            name='seva_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seva',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
