# Generated by Django 5.2.15 on 2026-08-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_seva_start_end_date'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='seva',
            new_name='bookings_se_start_d_80a456_idx',
            old_name='bookings_se_start_d_idx',
        ),
        migrations.RenameIndex(
            model_name='seva',
            new_name='bookings_se_is_acti_c04527_idx',
            old_name='bookings_se_is_acti_idx',
        ),
    ]
