# Generated by Django 5.2.15 on 2026-08-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_livedarshan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livedarshan',
            options={'ordering': ['-start_datetime', '-created_at']},
        ),
        migrations.AlterField(
            model_name='livedarshan',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livedarshan',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livedarshan',
            name='title',
            field=models.CharField(blank=True, default='Live Ganpati Darshan', max_length=200),
        ),
    ]
