# Generated by Django 6.0.7 on 2026-07-25 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devotees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('donor_name', models.CharField(blank=True, default='', max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.CharField(choices=[('general', 'General Fund'), ('annadaan', 'Annadaan'), ('construction', 'Construction'), ('education', 'Education')], default='general', max_length=30)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('devotee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='devotees.devotee')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['donation_code'], name='donations_d_donatio_3fca06_idx'), models.Index(fields=['purpose'], name='donations_d_purpose_e60597_idx')],
            },
        ),
    ]
