# Generated by Django 6.0.7 on 2026-07-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('expected_visitors', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('confirmed', 'Confirmed'), ('upcoming', 'Upcoming'), ('completed', 'Completed')], default='planning', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['event_code'], name='events_even_event_c_bd949b_idx'), models.Index(fields=['status'], name='events_even_status_5709b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('zone', models.CharField(blank=True, default='', max_length=100)),
                ('party_size', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('inside', 'Inside'), ('exited', 'Exited')], default='inside', max_length=20)),
            ],
            options={
                'ordering': ['-check_in'],
                'indexes': [models.Index(fields=['visitor_code'], name='events_visi_visitor_bf0dd5_idx'), models.Index(fields=['status'], name='events_visi_status_6efd29_idx')],
            },
        ),
    ]
