# Generated by Django 5.2.15 on 2026-08-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devotees', '0002_devotee_registration_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devotee',
            new_name='devotees_de_mobile_552e58_idx',
            old_name='devotees_de_mobile_2f6b41_idx',
        ),
    ]
