# Generated by Django 5.2.15 on 2026-08-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotees', '0003_rename_devotees_de_mobile_2f6b41_idx_devotees_de_mobile_552e58_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotee',
            name='guest_count',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
