# Generated by Django 5.2.15 on 2026-07-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
