/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplyVolunteerRouteImport } from './routes/apply-volunteer'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VolunteerSignupRouteImport } from './routes/volunteer-signup'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminCommandRouteImport } from './routes/admin.command'
import { Route as AdminCommunicationRouteImport } from './routes/admin.communication'
import { Route as AdminDevoteesRouteImport } from './routes/admin.devotees'
import { Route as AdminDonationsRouteImport } from './routes/admin.donations'
import { Route as AdminDutiesRouteImport } from './routes/admin.duties'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminPlatformRouteImport } from './routes/admin.platform'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSevasRouteImport } from './routes/admin.sevas'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminVisitorsRouteImport } from './routes/admin.visitors'
import { Route as AdminVolunteerApprovalsRouteImport } from './routes/admin.volunteer-approvals'
import { Route as AdminVolunteersRouteImport } from './routes/admin.volunteers'
import { Route as VolunteerDutiesRouteImport } from './routes/volunteer.duties'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyVolunteerRoute = ApplyVolunteerRouteImport.update({
  id: '/apply-volunteer',
  path: '/apply-volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerSignupRoute = VolunteerSignupRouteImport.update({
  id: '/volunteer-signup',
  path: '/volunteer-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommandRoute = AdminCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunicationRoute = AdminCommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevoteesRoute = AdminDevoteesRouteImport.update({
  id: '/devotees',
  path: '/devotees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonationsRoute = AdminDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDutiesRoute = AdminDutiesRouteImport.update({
  id: '/duties',
  path: '/duties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlatformRoute = AdminPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSevasRoute = AdminSevasRouteImport.update({
  id: '/sevas',
  path: '/sevas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVisitorsRoute = AdminVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVolunteerApprovalsRoute = AdminVolunteerApprovalsRouteImport.update({
  id: '/volunteer-approvals',
  path: '/volunteer-approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVolunteersRoute = AdminVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AdminRoute,
} as any)
const VolunteerDutiesRoute = VolunteerDutiesRouteImport.update({
  id: '/volunteer/duties',
  path: '/volunteer/duties',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply-volunteer': typeof ApplyVolunteerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/volunteer-signup': typeof VolunteerSignupRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/command': typeof AdminCommandRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/devotees': typeof AdminDevoteesRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/duties': typeof AdminDutiesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/platform': typeof AdminPlatformRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sevas': typeof AdminSevasRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/admin/volunteer-approvals': typeof AdminVolunteerApprovalsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/volunteer/duties': typeof VolunteerDutiesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply-volunteer': typeof ApplyVolunteerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/volunteer-signup': typeof VolunteerSignupRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/command': typeof AdminCommandRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/devotees': typeof AdminDevoteesRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/duties': typeof AdminDutiesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/platform': typeof AdminPlatformRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sevas': typeof AdminSevasRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/admin/volunteer-approvals': typeof AdminVolunteerApprovalsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/volunteer/duties': typeof VolunteerDutiesRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply-volunteer': typeof ApplyVolunteerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/volunteer-signup': typeof VolunteerSignupRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/command': typeof AdminCommandRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/devotees': typeof AdminDevoteesRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/duties': typeof AdminDutiesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/platform': typeof AdminPlatformRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sevas': typeof AdminSevasRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/admin/volunteer-approvals': typeof AdminVolunteerApprovalsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/volunteer/duties': typeof VolunteerDutiesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply-volunteer'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/volunteer-signup'
    | '/admin/ai'
    | '/admin/bookings'
    | '/admin/cms'
    | '/admin/command'
    | '/admin/communication'
    | '/admin/devotees'
    | '/admin/donations'
    | '/admin/duties'
    | '/admin/events'
    | '/admin/inventory'
    | '/admin/platform'
    | '/admin/reports'
    | '/admin/sevas'
    | '/admin/tasks'
    | '/admin/visitors'
    | '/admin/volunteer-approvals'
    | '/admin/volunteers'
    | '/volunteer/duties'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply-volunteer'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/volunteer-signup'
    | '/admin/ai'
    | '/admin/bookings'
    | '/admin/cms'
    | '/admin/command'
    | '/admin/communication'
    | '/admin/devotees'
    | '/admin/donations'
    | '/admin/duties'
    | '/admin/events'
    | '/admin/inventory'
    | '/admin/platform'
    | '/admin/reports'
    | '/admin/sevas'
    | '/admin/tasks'
    | '/admin/visitors'
    | '/admin/volunteer-approvals'
    | '/admin/volunteers'
    | '/volunteer/duties'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply-volunteer'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/volunteer-signup'
    | '/admin/ai'
    | '/admin/bookings'
    | '/admin/cms'
    | '/admin/command'
    | '/admin/communication'
    | '/admin/devotees'
    | '/admin/donations'
    | '/admin/duties'
    | '/admin/events'
    | '/admin/inventory'
    | '/admin/platform'
    | '/admin/reports'
    | '/admin/sevas'
    | '/admin/tasks'
    | '/admin/visitors'
    | '/admin/volunteer-approvals'
    | '/admin/volunteers'
    | '/volunteer/duties'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplyVolunteerRoute: typeof ApplyVolunteerRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  VolunteerSignupRoute: typeof VolunteerSignupRoute
  VolunteerDutiesRoute: typeof VolunteerDutiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-volunteer': {
      id: '/apply-volunteer'
      path: '/apply-volunteer'
      fullPath: '/apply-volunteer'
      preLoaderRoute: typeof ApplyVolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer-signup': {
      id: '/volunteer-signup'
      path: '/volunteer-signup'
      fullPath: '/volunteer-signup'
      preLoaderRoute: typeof VolunteerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/command': {
      id: '/admin/command'
      path: '/command'
      fullPath: '/admin/command'
      preLoaderRoute: typeof AdminCommandRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communication': {
      id: '/admin/communication'
      path: '/communication'
      fullPath: '/admin/communication'
      preLoaderRoute: typeof AdminCommunicationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/devotees': {
      id: '/admin/devotees'
      path: '/devotees'
      fullPath: '/admin/devotees'
      preLoaderRoute: typeof AdminDevoteesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/donations': {
      id: '/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AdminDonationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/duties': {
      id: '/admin/duties'
      path: '/duties'
      fullPath: '/admin/duties'
      preLoaderRoute: typeof AdminDutiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/platform': {
      id: '/admin/platform'
      path: '/platform'
      fullPath: '/admin/platform'
      preLoaderRoute: typeof AdminPlatformRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sevas': {
      id: '/admin/sevas'
      path: '/sevas'
      fullPath: '/admin/sevas'
      preLoaderRoute: typeof AdminSevasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/visitors': {
      id: '/admin/visitors'
      path: '/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof AdminVisitorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/volunteer-approvals': {
      id: '/admin/volunteer-approvals'
      path: '/volunteer-approvals'
      fullPath: '/admin/volunteer-approvals'
      preLoaderRoute: typeof AdminVolunteerApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/volunteers': {
      id: '/admin/volunteers'
      path: '/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AdminVolunteersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/volunteer/duties': {
      id: '/volunteer/duties'
      path: '/volunteer/duties'
      fullPath: '/volunteer/duties'
      preLoaderRoute: typeof VolunteerDutiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminCommandRoute: typeof AdminCommandRoute
  AdminCommunicationRoute: typeof AdminCommunicationRoute
  AdminDevoteesRoute: typeof AdminDevoteesRoute
  AdminDonationsRoute: typeof AdminDonationsRoute
  AdminDutiesRoute: typeof AdminDutiesRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminPlatformRoute: typeof AdminPlatformRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSevasRoute: typeof AdminSevasRoute
  AdminTasksRoute: typeof AdminTasksRoute
  AdminVisitorsRoute: typeof AdminVisitorsRoute
  AdminVolunteerApprovalsRoute: typeof AdminVolunteerApprovalsRoute
  AdminVolunteersRoute: typeof AdminVolunteersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminCommandRoute: AdminCommandRoute,
  AdminCommunicationRoute: AdminCommunicationRoute,
  AdminDevoteesRoute: AdminDevoteesRoute,
  AdminDonationsRoute: AdminDonationsRoute,
  AdminDutiesRoute: AdminDutiesRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminPlatformRoute: AdminPlatformRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSevasRoute: AdminSevasRoute,
  AdminTasksRoute: AdminTasksRoute,
  AdminVisitorsRoute: AdminVisitorsRoute,
  AdminVolunteerApprovalsRoute: AdminVolunteerApprovalsRoute,
  AdminVolunteersRoute: AdminVolunteersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplyVolunteerRoute: ApplyVolunteerRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  VolunteerSignupRoute: VolunteerSignupRoute,
  VolunteerDutiesRoute: VolunteerDutiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
