# Generated by Django 5.2.15 on 2026-07-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('important', 'Important')], max_length=20),
        ),
    ]
