# Generated by Django 5.2.15 on 2026-07-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_announcement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('important', 'Important')], max_length=20),
        ),
    ]
