# Generated by Django 5.2.15 on 2026-07-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_galleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['order'], name='content_faq_order_f71340_idx'), models.Index(fields=['is_published'], name='content_faq_is_publ_cd2a9f_idx')],
            },
        ),
    ]
