# Generated by Django 5.2.15 on 2026-07-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_newspost'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('established_year', models.CharField(blank=True, default='', max_length=10)),
                ('registration', models.CharField(blank=True, default='', max_length=255)),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('about', models.TextField(blank=True, default='')),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('alt_phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='temple/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
