# Generated by Django 5.2.15 on 2026-08-04 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdThresholds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_max', models.PositiveIntegerField(default=500)),
                ('moderate_max', models.PositiveIntegerField(default=1500)),
            ],
            options={
                'verbose_name': 'Crowd thresholds',
                'verbose_name_plural': 'Crowd thresholds',
            },
        ),
        migrations.CreateModel(
            name='DevoteeQRStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('devotee_name', models.CharField(blank=True, max_length=150)),
                ('is_inside', models.BooleanField(default=False)),
                ('last_entry_at', models.DateTimeField(blank=True, null=True)),
                ('last_exit_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrowdStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_area', models.CharField(max_length=120, unique=True)),
                ('crowd_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='low', max_length=10)),
                ('approx_visitors', models.PositiveIntegerField(default=0)),
                ('wait_time', models.PositiveIntegerField(default=0, help_text='Expected waiting time, in minutes')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, help_text='Active/inactive — inactive rows are hidden from the live dashboard')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crowd_status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Crowd statuses',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QRScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(db_index=True, max_length=64)),
                ('scan_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=5)),
                ('gate', models.CharField(blank=True, help_text='e.g. Main Gate, Gate 2', max_length=80)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerAreaAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_area', models.CharField(max_length=120)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='area_assignment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
