# Generated by Django 5.2.15 on 2026-08-04 03:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_status', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devoteeqrstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devoteeqrstatus',
            name='devotee',
            field=models.OneToOneField(blank=True, help_text='The devotee this QR code belongs to. Null only for codes issued outside a login (e.g. a walk-in printed pass).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
