# Generated by Django 5.2.15 on 2026-08-04 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_status', '0002_devoteeqrstatus_created_at_devoteeqrstatus_devotee'),
        ('devotees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devoteeqrstatus',
            name='devotee_name',
        ),
        migrations.AlterField(
            model_name='devoteeqrstatus',
            name='devotee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_status', to='devotees.devotee'),
        ),
        migrations.AlterField(
            model_name='devoteeqrstatus',
            name='qr_code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
