# Generated by Django 5.2.15 on 2026-08-05 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_status', '0003_remove_devoteeqrstatus_devotee_name_and_more'),
        ('devotees', '0003_rename_devotees_de_mobile_2f6b41_idx_devotees_de_mobile_552e58_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('area', models.CharField(blank=True, help_text='Gate or area where entry was granted', max_length=120)),
                ('devotee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_logs', to='devotees.devotee')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_in_at'],
                'indexes': [models.Index(fields=['devotee', 'checked_in_at'], name='crowd_statu_devotee_f2a5e9_idx')],
            },
        ),
    ]
