# Generated by Django 5.2.15 on 2026-08-06 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_status', '0004_entrylog'),
        ('devotees', '0003_rename_devotees_de_mobile_2f6b41_idx_devotees_de_mobile_552e58_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_qr', models.TextField(blank=True, help_text='Raw string received from the scanner — kept for audit/forensics.')),
                ('user_type', models.CharField(blank=True, choices=[('devotee', 'Devotee'), ('volunteer', 'Volunteer')], max_length=10)),
                ('scan_method', models.CharField(choices=[('QR', 'QR'), ('MANUAL', 'Manual')], default='QR', max_length=10)),
                ('action_type', models.CharField(blank=True, max_length=20)),
                ('booking_reference', models.CharField(blank=True, max_length=40)),
                ('scan_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('scan_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=10)),
                ('device_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('response_message', models.CharField(blank=True, max_length=255)),
                ('devotee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_history', to='devotees.devotee')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scan_time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out')], max_length=10)),
                ('scan_method', models.CharField(choices=[('QR', 'QR'), ('MANUAL', 'Manual')], default='QR', max_length=10)),
                ('booking_reference', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('devotee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='devotees.devotee')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['devotee', 'timestamp'], name='crowd_statu_devotee_38c48e_idx')],
            },
        ),
    ]
