# Generated by Django 5.2.15 on 2026-08-06 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_status', '0005_scanhistory_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrylog',
            name='devotee',
        ),
        migrations.RemoveField(
            model_name='entrylog',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='qrscanevent',
            name='scanned_by',
        ),
        migrations.DeleteModel(
            name='DevoteeQRStatus',
        ),
        migrations.DeleteModel(
            name='EntryLog',
        ),
        migrations.DeleteModel(
            name='QRScanEvent',
        ),
    ]
