# Generated by Django 5.2.15 on 2026-08-06 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_status', '0006_remove_entrylog_devotee_remove_entrylog_volunteer_and_more'),
        ('devotees', '0003_rename_devotees_de_mobile_2f6b41_idx_devotees_de_mobile_552e58_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevoteeQRStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_qr_token', models.TextField()),
                ('meal_qr_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('devotee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_status', to='devotees.devotee')),
            ],
            options={
                'verbose_name_plural': 'Devotee QR statuses',
            },
        ),
        migrations.CreateModel(
            name='MealCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10)),
                ('devotee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_collections', to='devotees.devotee')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_collections_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['devotee', 'timestamp'], name='crowd_statu_devotee_4dcb6c_idx')],
            },
        ),
    ]
