# Generated by Django 5.2.15 on 2026-08-07 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_status', '0007_devoteeqrstatus_mealcollection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_area', models.CharField(max_length=120)),
                ('action', models.CharField(choices=[('INCREMENT', 'Increment'), ('DECREMENT', 'Decrement')], max_length=10)),
                ('count', models.PositiveIntegerField(default=1)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_counter_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['assigned_area', 'timestamp'], name='crowd_statu_assigne_1686de_idx')],
            },
        ),
    ]
